package AnalizadorSint;

import java_cup.runtime.Symbol;

parser code
{:
    private Symbol s;

    public void syntax_error(Symbol s){
        this.s = s;
    }

    public Symbol getS(){
        return this.s;
    }
:};

terminal Truncate,Table,On,Asc,Desc,Where,And,In,Is,Not,Or,Null,As,Default,Set,FloatR,Varchar,IntR,BitR,Declare,
Go,Id,Bit,Int,Float,String,Punto,Coma,Punto_Coma,Igual,Parentesis_a,Parentesis_c,Mas,Menos,Asterisco,Dividir,Comparador,
Error,Var,From,Distinct,Cuadro,Bracket_a,Bracket_c,Select,Avg,Min,Max,Count,Sum,Join,Inner,Left,Outer,Right,Full,
Commit,All,Insert,Top,Percent,Into,Openquery,Values,Group,Order,By,Begin,Tran,Transaction,Rollback,Save;

non terminal  INICIO,SENTENCIA,DML,DDL,TCL,TSQL,SELECT,ASC,
              INSERT,TRUNCATE,TABLENAME,DATABASE_NAMES,WHERE_INDEX,COLUMN_NAMES_ASC,FILTER,CONJUNCT,
              DISJUNCT,COMPARACION,CONSTANT,CONSTANTS,COMPARADOR,FIN,COLUMN_EXPRESION,T,F,
              TOP,PERCENT,INTO,OBJECT,TABLENAME_2,COLUMN_LIST,VALUES,VALUES_OPTIONS,VALUES_OPTION,VALUES_2,
              ALL_DISTINCT,SELECT_LIST,CAMPO_AS,CAMPO,ALIAS,ID_M,METHOD,METHOD_NAME,
              PARAMETROS,FROM,JOINS,JOIN,JOIN_TYPE,TABLENAME_3,GROUP_BY,ORDER_BY,BEGIN,COMMIT,ROLLBACK,SAVEPOINT,TRAN;

start with INICIO;

INICIO ::= SENTENCIA FIN;
SENTENCIA ::= DML|DDL|TCL|TSQL;

TCL ::= BEGIN|COMMIT|ROLLBACK|SAVEPOINT;
BEGIN ::= Begin TRAN Var|Begin TRAN Var Id;
TRAN::= Tran|Transaction;
COMMIT ::= Commit TRAN|Commit|Commit TRAN Var|Commit TRAN Id;
ROLLBACK ::= Rollback TRAN|Rollback TRAN Var|Rollback TRAN Id;
SAVEPOINT ::= Save TRAN|Save TRAN Var|Save TRAN Id;

//---------------------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------------------
//DML------------------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------------------

DML ::= INSERT;

//---------------------------------------------------------------------------------------------------------------------------------
//SELECT --------------------------------------------------------------------------------------------------------------------------
// --------------------------------------------------------------------------------------------------------------------------------

SELECT ::= Select ALL_DISTINCT TOP SELECT_LIST FROM WHERE_INDEX GROUP_BY ORDER_BY|Select TOP SELECT_LIST FROM WHERE_INDEX GROUP_BY ORDER_BY;
ALL_DISTINCT ::= All|Distinct;
SELECT_LIST ::= CAMPO_AS| CAMPO_AS Coma SELECT_LIST;
CAMPO_AS ::= CAMPO ALIAS;
CAMPO ::= Asterisco|Id Punto Asterisco|Id Punto Id|Id Cuadro Id|METHOD|Id;
ALIAS ::= As Id| Id | As Bracket_a ID_M Bracket_c;
ID_M ::= Id|Id ID_M;
METHOD ::= METHOD_NAME Parentesis_a PARAMETROS Parentesis_c;
METHOD_NAME ::= Avg|Min|Max|Count|Sum;
PARAMETROS ::= COLUMN_EXPRESION| COLUMN_EXPRESION Coma PARAMETROS;
FROM ::= From TABLENAME ALIAS|From TABLENAME JOINS|From TABLENAME ALIAS JOINS|From TABLENAME;
JOINS ::= JOIN|JOIN JOINS|Parentesis_a JOIN Parentesis_c|Parentesis_a JOIN JOINS Parentesis_c;
JOIN ::= JOIN_TYPE CAMPO_AS On CAMPO Igual CAMPO| JOIN_TYPE CAMPO_AS On TABLENAME Comparador TABLENAME;
JOIN_TYPE ::= Join|Full Outer Join|Full Join|Left Join|Left Outer Join|Right Join|Right Outer Join| Inner Join;  
GROUP_BY ::= Group By DATABASE_NAMES|;
ORDER_BY ::= Order By COLUMN_NAMES_ASC|;
COLUMN_NAMES_ASC ::= Id ASC|Id ASC Coma COLUMN_NAMES_ASC;
ASC ::= Asc|Desc|;

//---------------------------------------------------------------------------------------------------------------------------------
//INSERT ---------------------------------------------------------------------------------------------------------------------------------
// ---------------------------------------------------------------------------------------------------------------------------------

INSERT ::= Insert TOP INTO OBJECT COLUMN_LIST VALUES_2;
TOP::= Top Parentesis_a COLUMN_EXPRESION Parentesis_c PERCENT|;
PERCENT ::= Percent|;
INTO ::= Into|;
OBJECT ::= TABLENAME_2|Openquery Parentesis_a Id Coma String Parentesis_c;
TABLENAME_2 ::= Id|Id Punto Id|Id Punto Id Punto Id|Id Punto Id Punto Id Punto Id;
COLUMN_LIST ::= Parentesis_a DATABASE_NAMES Parentesis_c|;
VALUES_2 ::= Values VALUES|Default Values|SELECT;
VALUES ::= Parentesis_a VALUES_OPTIONS Parentesis_c |Parentesis_a VALUES_OPTIONS Parentesis_c Coma VALUES;
VALUES_OPTIONS ::= VALUES_OPTION|VALUES_OPTION Coma VALUES_OPTIONS;
VALUES_OPTION ::= Default Values|Null|COLUMN_EXPRESION;

//---------------------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------------------
//DDL------------------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------------------

DDL ::= TRUNCATE;

//---------------------------------------------------------------------------------------------------------------------------------
//TRUNCATE---------------------------------------------------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------------------

TRUNCATE ::= Truncate Table TABLENAME;


DATABASE_NAMES ::= Id|Id Coma DATABASE_NAMES;
TABLENAME ::= Id|Id Punto Id|Id Punto Id Punto Id;
TABLENAME_3 ::= Id Punto Id|Id Punto Id Punto Id;

WHERE_INDEX ::= Where FILTER|;
FILTER ::= CONJUNCT | CONJUNCT And FILTER |CONJUNCT Or FILTER;
CONJUNCT ::= DISJUNCT|COMPARACION;
DISJUNCT ::= Id In Parentesis_a CONSTANTS Parentesis_c;
CONSTANTS ::= CONSTANT|CONSTANT Coma CONSTANTS;
CONSTANT ::= Int|String|Bit|Float|Null;
COMPARACION ::= COLUMN_EXPRESION COMPARADOR COLUMN_EXPRESION|TABLENAME_3 COMPARADOR COLUMN_EXPRESION;
COMPARADOR ::= Comparador|Igual|Is|Is Not;

COLUMN_EXPRESION ::= COLUMN_EXPRESION Mas T|COLUMN_EXPRESION Menos T|T;
T ::= T Asterisco F| T Dividir F|F;
F ::= Int|Float|Bit|String|Id|Var|Parentesis_a COLUMN_EXPRESION Parentesis_c;

FIN ::= Punto_Coma|Go;

