
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 16 15:25:51 CST 2019
//----------------------------------------------------

package AnalizadorSint;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Parentesis_c = 33;
  public static final int Parentesis_a = 32;
  public static final int Into = 63;
  public static final int Menos = 35;
  public static final int Full = 57;
  public static final int Coma = 29;
  public static final int Where = 7;
  public static final int Punto = 28;
  public static final int Default = 15;
  public static final int Count = 50;
  public static final int Bracket_c = 45;
  public static final int BitR = 20;
  public static final int Bracket_a = 44;
  public static final int IntR = 19;
  public static final int Max = 49;
  public static final int Mas = 34;
  public static final int FloatR = 17;
  public static final int Int = 25;
  public static final int Asterisco = 36;
  public static final int Avg = 47;
  public static final int Values = 65;
  public static final int Null = 13;
  public static final int Bit = 24;
  public static final int Tran = 70;
  public static final int Punto_Coma = 30;
  public static final int Varchar = 18;
  public static final int Insert = 60;
  public static final int String = 27;
  public static final int Begin = 69;
  public static final int Commit = 58;
  public static final int Transaction = 71;
  public static final int Set = 16;
  public static final int Desc = 6;
  public static final int Save = 73;
  public static final int Outer = 55;
  public static final int Group = 66;
  public static final int Is = 10;
  public static final int Right = 56;
  public static final int Table = 3;
  public static final int In = 9;
  public static final int And = 8;
  public static final int Or = 12;
  public static final int On = 4;
  public static final int Truncate = 2;
  public static final int Id = 23;
  public static final int EOF = 0;
  public static final int Distinct = 42;
  public static final int Left = 54;
  public static final int By = 68;
  public static final int From = 41;
  public static final int Inner = 53;
  public static final int Declare = 21;
  public static final int error = 1;
  public static final int Top = 61;
  public static final int Asc = 5;
  public static final int Comparador = 38;
  public static final int Cuadro = 43;
  public static final int Error = 39;
  public static final int Float = 26;
  public static final int Join = 52;
  public static final int Sum = 51;
  public static final int As = 14;
  public static final int Select = 46;
  public static final int All = 59;
  public static final int Rollback = 72;
  public static final int Go = 22;
  public static final int Openquery = 64;
  public static final int Not = 11;
  public static final int Percent = 62;
  public static final int Igual = 31;
  public static final int Var = 40;
  public static final int Min = 48;
  public static final int Order = 67;
  public static final int Dividir = 37;
}

